### ISSUE TITLE
iOS validation not working

### ISSUE THREAD

**Issue by wverdese** [Wizcorp/node-iap#19]
While I'm using this library for Google validation with no problems, I can't find a way to make it work with Apple.

I'm getting the receipt as Apple's documentation says:
*To retrieve the receipt data, use the appStoreReceiptURL method of NSBundle to locate the app’s receipt, and then read the entire file. If the appStoreReceiptURL method is not available, you can fall back to the value of a transaction's transactionReceipt property for backward compatibility.*

The result is a VERY LOOONG string:
MIIT3AYJKoZIhvcNAQcCoIITzTCCE8kCAQExCzAJBgUrDgMCGgUAMIIDjQYJKoZIhvcNAQcBoIIDfgSCA3oxggN2MAoCAQgCAQEEAhYAMAoCARQCAQEEAgwAMAsCAQECAQEEAwIBADALAgELAgEBBAMCAQAwCwIBDgIBAQQDA... *//truncated for obvious reasons*

That I'm passing AS IS as the receipt string:
*The receipt string passed may be either the base64 string that Apple really wants, or the decoded receipt as returned by the iOS SDK (in which case it will be automatically base64 serialized).*

I'm also passing productId and package name:
*Both productId and packageName (bundle ID) are optional, but when provided will be tested against. If the receipt does not match the provided values, an error will be returned.*

The call fails with this message:
*The data in the receipt-data property was malformed or missing.*

Is it something that I'm doing wrong?

Thanks,
Walt

**Comment by ronkorving** [comment]
Can you show how you call the `iap` APIs? A code sample says more than a thousand words.

**Comment by wverdese** [comment]
```javascript
var authorizeRequest = function(req, res, callback) {
	var platform = req.param('platform'); // apple || google
	if (!platform) {
		res.status(400).send('param "platform" is required');
		return;
	}
	var receipt = req.param('receipt');
	if (!receipt) {
		res.status(400).send('param "receipt" is required');
		return;
	}
	var product = req.param('product');
	if (!product) {
		res.status(400).send('param "product" is required');
		return;
	}
	var package_name = req.param('package_name');
	if (!package_name) {
		res.status(400).send('param "package_name" is required');
		return;
	}

	var payment = {
	    receipt: receipt,   					  // always required 
	    productId: product, 					  // optional for apple
	    packageName: package_name 				  //optional for apple
	};

	if (platform == 'google')
	{
		payment.keyObject = fs.readFileSync(googleJSONKey); // only google
	}
 
	iap.verifyPayment(platform, payment, function (err, response) {
		if (err) {
			console.log(err.message);
			res.status(401).send(err.message);
		} else {
			callback(req, res);
		}
	});
}
```

I'm calling this in my route, for a GET method. Params are passed URLEncoded in the request from the client. In `callback` there's the code I want to execute only if the payment is verified. As I said, this is working for google.

**Comment by ronkorving** [comment]
I would like to see *your* code. How are you calling this?

**Comment by wverdese** [comment]
You mean *the client*'s code? Here it is:
```Objective-C
[[AFHTTPRequestOperationManager manager] GET:url
parameters:@{@"platform" : @"apple", @"receipt" : [[NSData
dataWithContentsOfURL:[[NSBundle mainBundle] appStoreReceiptURL]]
base64EncodedStringWithOptions:
NSDataBase64Encoding64CharacterLineLength], @"product" :appleStoreId,
@"package_name": [[NSBundle mainBundle] bundleIdentifier]}
success:^(AFHTTPRequestOperation *operation, NSDictionary*
responseObject) {
 } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
 }];
```

**Comment by ronkorving** [comment]
Apologies, I was looking at it from the tiny screen on my phone and it wasn't clear. Your first code sample was fine. Let me get back to you on that.

**Comment by wverdese** [comment]
That was the first thing I thought, but from the server logs the string is entire.
I need to change a lot to have a service in POST to pass the receipt here so I wanted to be sure that this is the problem.

**Comment by ronkorving** [comment]
Can you decode the base64 string and is it valid JSON?

**Comment by wverdese** [comment]
I tried to pass the copy/pasted base64 string instead of reading it from the parameters and the validation worked! So it's clearly a problem in the parameter passing, even though I don't know which. Your library is working, though. Thanks for the support!

**Comment by ronkorving** [comment]
Base 64 contains the plus (+) symbol for example which is interpreted as a space. Before sending a query string like that, make sure to use encodeURIComponent first. Good luck!
