### ISSUE TITLE
Update Github description to match package.json

### ISSUE THREAD

**Issue by KLVTZ** [Wizcorp/node-iap#35]
This should help clients find this package with the available platforms listed. For example:

`In-app purchases for Node.js (Apple, Google, Amazon, Roku)`

**Comment by ronkorving** [comment]
Sure. Wanna make a PR? :)

**Comment by ronkorving** [comment]
Changed both to:

> In-app purchase validation for Apple, Google, Amazon, Roku

I figured the "Node.js" bit was kind of obvious from:

- On GitHub: the repo name
- On NPM: the fact that it's on NPM :)
