### ISSUE TITLE
[Google] - use oderId instead of the token as transationId

### ISSUE THREAD

**Issue by adrian-gierakowski** [Wizcorp/node-iap#44]
`orderId` not the `token` should be the property used as `transactionId`

the Google `token` is more like the Apples base64 encoded `receipt`: both enable the developer to fetch updated information about users purchase/subscription. Googles `orderId` is the property which corresponds to Apples `transaction_id`. 

its the `orderId` that uniquely identifies each transaction made by the user. What you are currently using as `transactionId` is the `token` which is used to fetch information from the api about given purchase/subscription. In case of renewing subscriptions, there will by more then one transaction associated with give `token`, each transaction having a unique `orderId` which corresponds to subsequent subscription periods. If you ever want to match data fetched from [googles purchases api](https://developers.google.com/android-publisher/api-ref/) with [play store sales & payout reports](https://support.google.com/googleplay/android-developer/answer/2482017?hl=en-GB) you will need to use the `orderId` not the `token`.

**Comment by KLVTZ** [comment]
Sounds like a good idea. 

Perhaps we can consolidate this change in #40

**Comment by KLVTZ** [comment]
@superandrew213 Gotcha, yeah maybe a better flow would be to review and merge #40 and then maybe consider this request in a different PR. If this will be a breaking change then maybe the PR would justify a semver upgrade from from the owner. Whatcha think @ronkorving?

**Comment by justinpage** [comment]
@adrian-gierakowski Are you still up for making a PR now that #40 is merged? As mentioned earlier, it should be marked as a breaking change.

**Comment by adrian-gierakowski** [comment]
@justinpage I'm on it

**Comment by adrian-gierakowski** [comment]
@justinpage I'll deal with #30 first
