### ISSUE TITLE
[Apple] Sandbox testing no longer works

### ISSUE THREAD

**Issue by dawidvdh** [Wizcorp/node-iap#49]
When I try and do a sandbox test with iOS, I receive the following error:

```
error { Error: getaddrinfo ENOTFOUND buy.itunes.apple.com buy.itunes.apple.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'buy.itunes.apple.com',
  host: 'buy.itunes.apple.com',
  port: 443 }
```

**Comment by justinpage** [comment]
@dawidvdh Are you still experience this issue? 
I can have this tested against the latest RC with our sandbox app.

**Comment by dawidvdh** [comment]
Hey @justinpage, I have no Idea had to switch to a different server based solution as I couldn't get this to work the last time I attempted it.

**Comment by Maxence-Machu** [comment]
@dawidvdh , are you using Firebase Functions ? 

If you do, you must enable Flame or Blaze formula in your account since Firebase Function doesn't allow external network requests when billing account is not configured.

> "Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions"

**Comment by justinpage** [comment]
@ronkorving I think we can close this issue.
