### ISSUE TITLE
[Apple] purchaseData should be purchaseDate

### ISSUE THREAD

**Issue by ronkorving** [Wizcorp/node-iap#51]
@superandrew213 Your commit https://github.com/Wizcorp/node-iap/commit/458c892358c1a51ac6db4a7868b854017c2d40ce added purchaseDate and expirationDate to all responses, which is great. I noticed however that sometimes it seems to return a property `purchaseData` instead of `purchaseDate`.

I think it's limited to Apple. Could you double check?

**Comment by justinpage** [comment]
Looks like this can be closed?

**Comment by superandrew213** [comment]
Yes, @ronkorving you can close this.

**Comment by ronkorving** [comment]
Indeed 👍
