### ISSUE TITLE
Remove response assertions?

### ISSUE THREAD

**Issue by innerdvations** [Wizcorp/node-iap#6]
When a receipt is sent from an app to the server, I need to perform some actions, and then respond to the app that it's ok to consume the purchase.

The problem is that this module is asserting that the purchase is already consumed.  That's not safe, because if the app buys then consumes the purchase before notifying the server, and then something goes wrong, the purchase has been (more or less) lost in the ether, since it will no longer appear in the list of purchases from Google after being consumed but will not have registered with the node server.

Any chance that line (along with the purchaseState line, in case we actually need to check on that info) could simply be removed?  Or if you have some external code depending on that check being there, add an alternative method for just checking the state of a purchase rather than verifying those exact conditions?

Thanks!

**Comment by ronkorving** [comment]
@AlmirKadric was responsible for the Google purchase implementation. Mind giving your feedback on this one, Almir? I assume @innerdvations is talking about https://github.com/Wizcorp/node-iap/blob/master/lib/google/index.js#L63

**Comment by AlmirKadric** [comment]
@innerdvations you do have a point, we should not be asserting the state of the purchase and should leave that to the application in question. I'll remove those 2 lines and make a release. Good with you @ronkorving?

**Comment by AlmirKadric** [comment]
feel free to review it here
https://github.com/Wizcorp/node-iap/pull/7

**Comment by ronkorving** [comment]
Works for me

**Comment by ronkorving** [comment]
Merged

**Comment by innerdvations** [comment]
Great, thanks for the quick response!
