### ISSUE TITLE
Use version 3 of the Google Play Developer API 

### ISSUE THREAD

**Issue by superandrew213** [Wizcorp/node-iap#61]
https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

**Comment by ronkorving** [comment]
@superandrew213 Thanks for the heads up!
Are you up for making a PR?

**Comment by shinlang** [comment]
Created a small PR here: https://github.com/Wizcorp/node-iap/pull/67

**Comment by JarnoVgr** [comment]
Support for v1 and v2 API's will be removed 1st of December 2019. PR #67 should really be merged.

**Comment by ronkorving** [comment]
Released 1.1.0!
