### ISSUE TITLE
npm - SIgnature Verification Bypass

### ISSUE THREAD

**Issue by eysteinbye** [Wizcorp/node-iap#62]
iap has a dependency of jwt-simple, and jwt-simple has a high severity vulnerability that is fixed in>=0.5.3

https://www.npmjs.com/advisories/831

Could you bump jwt-simple?

**Comment by ronkorving** [comment]
I'm quite AFK for another week, but would happily merge a PR :)

**Comment by ndangles** [comment]
#63
